name: Publish Docker image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    branches: [master]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6.2
        with:
          dockerfile: ./Dockerfile
          image: applydu_qrcode
          tags: ${{ steps.meta.outputs.tags }}
          registry: ${{ secrets.DOCKERHUB_REPO }}
          labels: ${{ steps.meta.outputs.labels }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}